apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.api.port | quote }}
      targetPort: {{ .Values.api.port | quote }}
  selector:
    app: {{ .Values.api.name }}
