apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name}}
    spec:
      containers:
      - name: {{ .Values.db.name}}
        image: {{ .Values.db.image}}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-secret
              key: password
        - name: MYSQL_DATABASE
          value: {{ .Values.db.name}}

        ports:
        - containerPort: {{ .Values.db.port | quote}}
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: db-pvc


