apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
    spec:
      containers:
        - name: {{ .Values.api.name }}
          image: {{ .Values.api.image }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env: 
            - name: DB_HOST
              value: {{ .Values.api.env.DB_HOST }}
            - name: DB_USER
              value: {{ .Values.api.env.DB_USER }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: password
            - name: DB_NAME
              value: {{ .Values.api.env.DB_NAME }}
            - name: DB_PORT 
              value: {{ .Values.api.env.DB_PORT | quote}}
